# Generated by Django 6.0.4 on 2026-04-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Qtd Original')),
                ('current_quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Qtd Atual')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Custo Unitário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='produtos.product', verbose_name='Produto')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.purchase', verbose_name='Compra Origem')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['created_at'],
            },
        ),
    ]
