# Generated by Django 6.0.4 on 2026-04-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='Unidade de Medida')),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Preço de Venda')),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Médio')),
                ('last_purchase_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Último Custo')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Estoque Atual')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('low_stock_alert', models.PositiveIntegerField(default=10, verbose_name='Alerta de Estoque Baixo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
