# Generated by Django 6.0.4 on 2026-04-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('status', models.CharField(choices=[('PENDING', 'Em Aberto (Caixa)'), ('COMPLETED', 'Finalizada (Baixa no Estoque)'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=15, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('CREDIT', 'Cartão de Crédito'), ('DEBIT', 'Cartão de Débito')], max_length=10, null=True, verbose_name='Forma de Pagamento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total da Venda')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clientes.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-date_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Custo no Momento (CMV)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total do Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendas.sale')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
