# Generated by Django 6.0.4 on 2026-04-14 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-issue_date', '-id'], 'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente (Em cotação / Aguardando entrega)'), ('COMPLETED', 'Concluída (Recebida e Estoque Atualizado)'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantidade Necessária')),
                ('justification', models.TextField(verbose_name='Justificativa / Observação')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Aprovação'), ('APPROVED', 'Aprovado (Liberado para Compra)'), ('REJECTED', 'Rejeitado pela Gerência'), ('COMPLETED', 'Atendido (Comprado)')], default='PENDING', max_length=15, verbose_name='Status da Solicitação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_evaluated', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.product', verbose_name='Produto Solicitado')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Compra',
                'verbose_name_plural': 'Solicitações de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='origin_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='compras.purchaserequest', verbose_name='Solicitação de Origem'),
        ),
    ]
